zipit-base-files: switch to a more openwrt-friendly init system and change preinit overlay
The updated init script system uses the original openwrt style minus procd support. Any
initscript that is designed to work with procd will not be enabled or run and instead
displays a message stating such.

The updated preinit runs fsck to check for errors on the SD card before mounting. If
errors are found it will reboot. If booting from SD Card (or USB), preinit mounts the
device as / and continues to regular init (skipping overlay mount).

When booting from internal flash, preinit attempts to mount the jffs. If that fails it
mounts a tmpfs to /overly instead and continues. If /etc/overlay.conf is found in jffs,
it attempts to mount the configured overlay. The configured overlay then becomes the
'upper' filesystem and takes all writes. The jffs is mounted in between root (squashfs)
and the configured overlay so that changes in jffs are applied if they exist. The
configured overlay device root is available in /mnt. All changes are written to the
'upperdir' configured in overlay.conf (see that file for instructions).

Signed-off-by: Joe Honold <mozzwald@gmail.com>

diff --git a/zipit-base-files/files/etc/preinit b/zipit-base-files/files/etc/preinit
--- a/zipit-base-files/files/etc/preinit
+++ b/zipit-base-files/files/etc/preinit
@@ -19,28 +19,29 @@ do_pivot() { # <new_root> <old_root>
 /bin/mount -t sysfs none /sys
 /bin/mount -t tmpfs none /tmp
 
-# Setup minimal dev
+# Setup dev
 /bin/mount -t tmpfs -o size=64k,mode=0755 none /dev
 /bin/mkdir -p /dev/pts
 /bin/mount -t devpts devpts /dev/pts
 /bin/mkdir -p /dev/shm
-/bin/mknod /dev/tty1 c 4 1
-/bin/mknod /dev/console c 5 1
-/bin/mknod /dev/null c 1 3
-/bin/mknod /dev/fb0 c 29 0
-/bin/mknod /dev/mtdblock3 b 31 3
-/bin/mknod /dev/mtdblock4 b 31 4
-/bin/mknod /dev/mmcblk0   b 179 0
-/bin/mknod /dev/mmcblk0p1 b 179 1
-/bin/mknod /dev/mmcblk0p2 b 179 2
+/bin/echo /sbin/mdev > /proc/sys/kernel/hotplug
+/sbin/mdev -s
 
-# If booting from SD Card, mount squashfs and jffs, skip overlay mount
-# and continue to regular init
-/bin/grep -q "root=/dev/mmcblk0p" /proc/cmdline
-if [ $? -eq 0 ]; then
+# If booting from anything other than internal flash,
+# skip overlay mount and continue to regular init
+rootdev=`/bin/cat /proc/cmdline | /bin/sed -e 's/^.*root=//' -e 's/ .*$//'`
+if [ "$rootdev" != "/dev/mtdblock3" ]; then
+	# check rootfs for errors
+	mount -o remount,ro /
+	/usr/sbin/e2fsck -y "$rootdev" &>/dev/tty0
+	if [ $? -eq 1 ] || [ $? -eq 2 ]; then
+		echo "e2fsck corrected errors on $rootdev, restarting..." >/dev/tty0
+		sleep 3
+	exec /sbin/reboot -f
+    fi
 	mount -o remount,rw /
-	mount -t squashfs /dev/mtdblock3 /rom
-	#mount -t jffs2 /dev/mtdblock4 /overlay
+	# Do not mount squash/jffs in case partition sizes are different.
+	# Potential data loss when mounting the writable jffs
 	exec /sbin/init
 fi
 
@@ -49,39 +50,74 @@ fi
 
 # Make temporary rootfs
 /bin/mount -t tmpfs none /rom
-/bin/mkdir -p /rom/overlay
+/bin/mkdir -p /overlay
 /bin/mkdir -p /mnt
 
-# Mount the jffs
-/bin/mount -t jffs2 -o rw,noatime /dev/mtdblock4 /rom/overlay
-jffsret=$?
-
-#TODO,MAYBE: implement overlay from loop device? (ie, image file from fat sd card)
-if [ -f "/rom/overlay/upper/etc/overlay.conf" ]; then
-	# Source overlay.conf from jffs if available
-	. /rom/overlay/upper/etc/overlay.conf
-	# Unmount jffs
-	/bin/umount /rom/overlay
-	#TODO: if fs is ext2-4, check for errors before mount
-	# Mount the filesystem from our modified config
-	/bin/mount -t $fstype -o rw,noatime $overlaydev /rom/overlay
-	configret=$?
-else
-	. /etc/overlay.conf
+# Mount the jffs partition
+/bin/mount -t jffs2 -o rw,noatime /dev/mtdblock4 /overlay
+if [ $? -ne 0 ]; then
+	# jffs partition was not mountable, mount tmpfs as
+	# overlay and show warning
+	/bin/mount -t tmpfs none /overlay
+	echo "Unable to mount jffs partition, mounting tmpfs overlay instead" >/dev/tty0
 fi
 
-#TODO: if jffs or configured overlay mount fails, something went wrong. do tmpfs overlay? just boot read only root?
+# Make our required overlay directories in jffs
+/bin/mkdir -p /overlay/upper
+/bin/mkdir -p /overlay/work
 
-# Make our required overlay directories if they do not exist
-/bin/mkdir -p /rom/overlay/$upperdir
-/bin/mkdir -p /rom/overlay/$workdir
+#FOR TESTING: exit preinit and run testinit
+if [ -f /overlay/upper/etc/testinit ]; then
+	exec /overlay/upper/etc/testinit
+fi
 
-# Mount the overlay
-/bin/mount -t overlay "/overlay" -o lowerdir=/,upperdir=/rom/overlay/$upperdir,workdir=/rom/overlay/$workdir /mnt
+confovpass=0
+mntdestdir=/overlay/mnt
+
+#TODO: implement overlay from loop device (ie, image file from fat sd card)
+if [ -f "/overlay/upper/etc/overlay.conf" ]; then
+	# Source overlay.conf from jffs partition (not squashfs)
+	. /overlay/upper/etc/overlay.conf
+
+	# if overlay device is mounted, unmount it so we can check for errors
+	if /bin/grep -qs "^/dev/$overlaydev " /proc/mounts ; then
+		umount "/dev/$overlaydev";
+	fi
+
+	# check fs for errors
+	/usr/sbin/e2fsck -y "/dev/$overlaydev" &>/dev/tty0
+
+	# Mount the filesystem from our overlay config
+	mkdir -p "$mntdestdir/$overlaydev"
+
+	if ! /bin/mount -t "$fstype" -o rw,noatime "/dev/$overlaydev" "$mntdestdir/$overlaydev" ; then
+		# Failed to mount configured overlay, clean up mountpoint
+		rmdir "$mntdestdir/$overlaydev"
+		echo "Failed to mount configured overlay!" >/dev/tty0
+		# Mount the jffs overlay only
+		/bin/mount -t overlay /overlay -o lowerdir=/,upperdir=/overlay/upper,workdir=/overlay/work /mnt
+	else	
+		# Make our required overlay directories
+		/bin/mkdir -p "$mntdestdir/$overlaydev/$upperdir"
+		/bin/mkdir -p "$mntdestdir/$overlaydev/$workdir"
+		# Mount the jffs and configured overlays; writes go to the configured overlay
+		/bin/mount -t overlay overlay -o lowerdir=/overlay/upper:/,upperdir="$mntdestdir/$overlaydev/$upperdir",workdir="$mntdestdir/$overlaydev/$workdir" /mnt
+		confovpass=1
+		echo "Mounted jffs and $overlaydev overlay" >/dev/tty0
+	fi
+else
+	# Mount the jffs overlay if no configured overlay
+	/bin/mount -t overlay /overlay -o lowerdir=/,upperdir=/overlay/upper,workdir=/overlay/work /mnt
+fi
 
 # pivot root
 do_pivot /mnt /rom
 
+# If configured overlay mount passed, move overlaydev mount to /mnt
+if [ $confovpass -eq 1 ]; then
+	mkdir -p "/mnt/$overlaydev"
+	/bin/mount -o noatime,move "$mntdestdir/$overlaydev" "/mnt/$overlaydev"
+fi
+
 # Continue to regular init
 exec /sbin/init
-
